# Generated by Django 3.1.7 on 2021-03-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210310_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
